<?php
// module/Album/view/album/album/index.phtml:

$title = 'Users';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('users', ['action' => 'add']) ?>">Add new user</a>
</p>

<table class="table">
<tr>
    <th>Username</th>
    <th>Actions</th>
</tr>
<?php foreach ($users as $user) : ?>
    <tr>
        <td><?= $this->escapeHtml($user->username) ?></td>
        <td>
            <a class="btn btn-success" href="<?= $this->url('users', ['action' => 'edit', 'id' => $user->id]) ?>">Edit</a>
            <a class="btn btn-danger" href="<?= $this->url('users', ['action' => 'delete', 'id' => $user->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>